default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: timekeeper_development

test:
  <<: *default
  database: timekeeper_test

production:
  <<: *default
  database: timekeeper_production